#!/usr/bin/env python
# -=-<[ Bismillahirrahmanirrahim ]>-=-
# -*- coding: utf-8 -*-
# @Date    : 2021-05-08 18:05:48
# @Author  : Dahir Muhammad Dahir
# @Description : something cool


from enum import Enum


class ActionStatus(str, Enum):
    success = "success"
    failed = "failed"


class Gender(str, Enum):
    male = "m"
    female = "f"
    na = "NA"


class LicenseValidity(str, Enum):
    valid = "valid"
    expired = "expired"

class UserStatus(str, Enum):
    enabled = "enabled"
    disabled = "disabled"


class TripStatus(str, Enum):
    not_started = "not_started"
    started = "started"
    cancelled = "cancelled"


class NINType(str, Enum):
    national = "national"
    autogenerated = "autogenerated"


class VehicleStatus(str, Enum):
    not_activated = "not activated"
    activated = "activated"
    deactivated = "deactivated"
    blacklisted = "blacklisted"


class WalletStatus(str, Enum):
    enabled = "enabled"
    disabled = "disabled"
    closed = "closed"

